# Generated by Django 4.2.16 on 2024-10-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_department', '0002_toy_picture_max_toy_picture_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='toy',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
