# Generated by Django 4.2.16 on 2024-10-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_department', '0003_alter_toy_cost_alter_toy_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
