# Generated by Django 4.2.16 on 2024-10-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_department', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='psw',
            field=models.CharField(default='', max_length=100),
        ),
    ]
