# Generated by Django 4.2.16 on 2024-10-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_department', '0011_buyer_psw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField()),
                ('toy_id', models.IntegerField()),
            ],
        ),
    ]
