# Generated by Django 4.2.16 on 2024-10-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_department', '0013_basket_toy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='toy_descr',
            field=models.CharField(default='', max_length=128),
        ),
    ]
